### PR TITLE
Fix compatibility with PHP 8 and Moodle 3.11

### PR DESCRIPTION
**Pull request by bwurst**
This pull requests incorporates PR #6 from @NunesGodinho (PHP 7) and a suggestion from the moodle tracker #CONTRIB-7783 (fix for recent moodle versions)

I fixed PHP 8 errors by myself

Additionally, I removed the quick links to past days/weeks/months because these lead to frustrating user experience. (It's a separate commit, you can choose for your own.)

### CODE REVIEW

**Comment by arborrow** [comment]
@bwurst Many thanks for this PR. I had not actively been maintaining this repository but would be happy to add you as a contributor if you would like help keep it updated. Peace - Anthony

**Comment by davosmith** [comment]
Noting that the pix_url() fixes while needed, are not quite correct, the lines should be updated to use pix_icon() instead.

Also, those changes are not compatible with earlier versions of Moodle, so the required version number will need updating, along with splitting out a separate branch for the version that is still compatible with earlier Moodle versions.

If you are removing specific functionality, then remove it - don't leave old code hanging around commented out (git is there in case anyone wants to go back and find it). It might be better to add a global setting so a site admin can choose whether or not they think the functionality in question is helpful or confusing.

**Comment by arborrow** [comment]
@davosmith Good to see you are still around and working on this and for your helpful comments. Peace - Anthony

**Comment by bwurst** [comment]
Okay, changed to use pix_icon() instead, hope that's been the right way?!
I reverted my commit about showing the past times, it's clearly a separate thing and I can keep this in a local branch.
When I search for pix_icon, I find docs for moodle 3.8, so I used this as required version. As nothing below 3.9 gets security support at the moment, I don't think this is important.

**Comment by bwurst** [comment]
We do not use this module in production (yet), I just had to make it work for presentation and discussion.
@arborrow Thank you for giving me collaborator access, but I'm not into moodle hacking either, so I hesitate to merge these changes here by myself. Would be great if anyone could have a look. 
If our school is going to use this - to be decided in near future - then I'll have a look at this again.

**Comment by davosmith** [comment]
I'm planning on reviewing over the weekend, I don't usually have spare time to do so during the week.

**Comment by davosmith** [comment]
I've reviewed the changes and they look reasonable.

I've not tested this by running the code, as, to be honest, I'm not actively updating / maintaining this code much these days (none of the customers who originally wanted me to handle the earlier upgrades have asked for any upgrades recently).

After merging, I'll bump up the plugin version number, to reflect the changes.

**Comment by arborrow** [comment]
@davosmith thanks for reviewing the pull request and your continued efforts to keep this block updated.

@bwurst - since davo is still actively maintaining this repository, I went ahead and removed you as a maintainer so as to allow him to have full control over it. We can always re-assess as appropriate later.

**Comment by bwurst** [comment]
Sure, I'm fine with this. Thank you both for your work!

**Pull request merged**
